### ISSUE TITLE
Wrong size with `with: 100%`

### ISSUE THREAD

**Issue by vcarel** [inokawa/rich-textarea#39]
**Describe the bug**
I would like to extend the width of RichTextarea to the size of the parent component, with `width: 100%`. But this results in a size of 0 + horizontal padding.

**To Reproduce**
```jsx
<RichTextarea style={{ border: "solid 2px grey", padding: "0.5rem", width: "100%" }} value="hello" />
```

results in: 

![image](https://user-images.githubusercontent.com/1541093/198595728-ac284d0b-74d1-45e9-b26c-fb1aea318273.png)

while the same without `width: 100%` results in:

![image](https://user-images.githubusercontent.com/1541093/198596003-3c60ad80-e440-42bf-a972-06b0f04fa8ea.png)

**Expected behavior**
RichtextArea should behave like textarea.

**Platform:**
 - OS: Linux
 - Browser: Chrome 107
 - Version of this package: 0.18.0

**Comment by vcarel** [comment]
Also, I notice a content jump on mount.

**Comment by vcarel** [comment]
For the record, I'm using the following work-around...

```tsx
  const rootRef = useRef<HTMLDivElement>()

  const observer = useMemo(
    () =>
      new ResizeObserver(() =>
        requestAnimationFrame(() => {
          if (rootRef.current) setWidth(rootRef.current.clientWidth)
        })
      ),
    []
  )

  useEffect(() => {
    const root = rootRef.current
    if (root) {
      observer.observe(root)
      return () => observer.unobserve(root)
    }
  }, [observer])

  const initRootRef = useCallback((node: HTMLDivElement) => {
    // Setting width early here prevents the textarea to flash at the wrong width
    setWidth(node.clientWidth)
    rootRef.current = node
  }, [])

  return (
    <div ref={initRootRef}>
      <RichTextarea
        ref={ref}
        style={{ border: "solid 2px grey", padding: "0.5rem", width }}
        value="hello"
      />
    </div>
  )
```

It is not perfect however, because we can observe a lag when the browser is resized. But it is better than nothing.

**Comment by inokawa** [comment]
Probably fixed in `0.18.1`.
Thank you for your reporting!

**Comment by vcarel** [comment]
I confirm. Many thank! that was fast 🥳

**Comment by vcarel** [comment]
Thanks for the fix!

But it's partially fixed. If I specify `style={{ width: 100% }}`, it works.
But I use CSS, like:

```
.w-full {
  width: 100%
}

<RichTextarea className="w-full" />
```

it doesn't.
